image: rust:latest

before_script:
  - apt update -y -qq
  - apt install -y -qq --no-install-recommends  git rustc cargo clang make pkg-config nettle-dev libssl-dev capnproto libsqlite3-dev ca-certificates valgrind strace python3-dev python3-setuptools python3-cffi python3-pytest gnupg
  - apt clean

Cargo test:
  stage: test
  script:
  - cargo test
