# SPDX-FileCopyrightText: 2019-2021 Heiko Schaefer <heiko@schaefer.name>
# SPDX-License-Identifier: GPL-3.0-or-later

[workspace]
members = [
    "openpgp-ca-lib",
    "openpgp-ca-bin",
    "openpgp-ca-restd",
    "gnupg-test-wrapper",
]
