# SPDX-FileCopyrightText: 2019-2020 Heiko Schaefer <heiko@schaefer.name>
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "openpgp-ca"
version = "0.1.3"
description = "OpenPGP CA is a tool for managing OpenPGP keys within organizations"
authors = ["Heiko Schaefer <heiko.schaefer@posteo.de>"]
license = "GPL-3.0-or-later"
categories = ["cryptography", "email"]
keywords = ["OpenPGP", "Sequoia", "PGP"]
homepage = "https://gitlab.com/openpgp-ca/openpgp-ca"
repository = "https://gitlab.com/openpgp-ca/openpgp-ca"
documentation = "https://openpgp-ca.gitlab.io/openpgp-ca/"
edition = "2018"

[lib]
name = "openpgp_ca_lib"
path = "src/lib.rs"

[[bin]]
name = "openpgp-ca"
path = "src/bin.rs"

[dependencies]
structopt = "0.3"
clap = "2.33"

diesel = { version = "1.4", features = ["sqlite"] }
diesel_migrations = "1.4"

lazy_static = "1.4"
dotenv = "0.15"
anyhow  = "1.0"
chrono = "0.4"

chbs = "0.0.8"
publicsuffix = "1.5"

sha2 = "0.9"

futures = "0.1"
tokio-core = "0.1"

sequoia-openpgp = { git = "https://gitlab.com/sequoia-pgp/sequoia.git", tag = "v0.18.0" }
sequoia-net = { git = "https://gitlab.com/sequoia-pgp/sequoia.git", tag = "v0.18.0" }
sequoia-core = { git = "https://gitlab.com/sequoia-pgp/sequoia.git", tag = "v0.18.0" }

#sequoia-openpgp = { git = "https://gitlab.com/sequoia-pgp/sequoia.git", rev = "4ec978c1" }
#sequoia-net = { git = "https://gitlab.com/sequoia-pgp/sequoia.git", rev = "4ec978c1" }
#sequoia-core = { git = "https://gitlab.com/sequoia-pgp/sequoia.git", rev = "4ec978c1" }

# tests
tempfile = "3.0"
csv = "1.1"
rexpect = "0.4"
