[package]
name = "openpgp-ca"
version = "0.1.1"
authors = ["Heiko Schaefer <heiko.schaefer@posteo.de>"]
edition = "2018"

[lib]
name = "openpgp_ca_lib"
path = "src/lib.rs"

[[bin]]
name = "openpgp-ca"
path = "src/bin.rs"

[dependencies]
clap = {version = "2.33", features = ["yaml"]}
diesel = { version = "1.4", features = ["sqlite","r2d2"] }
diesel_migrations = "1.4"

lazy_static = "1.4"
dotenv = "0.15"
failure = "0.1"
chrono = "0.4"

publicsuffix = "1.5"

futures = "0.1"
tokio-core = "0.1"

#sequoia-openpgp = "0.13.0"

sequoia-openpgp = { git = "https://gitlab.com/sequoia-pgp/sequoia.git", rev = "b9b6533b" }
sequoia-net = { git = "https://gitlab.com/sequoia-pgp/sequoia.git", rev = "b9b6533b" }
sequoia-core = { git = "https://gitlab.com/sequoia-pgp/sequoia.git", rev = "b9b6533b" }

# tests
tempfile = "3.0"
csv = "1.1"
rexpect = "0.3"
