# SPDX-FileCopyrightText: 2021 Danny Grove <danny@drgrovellc.com>
# SPDX-License-Identifier: GPL-3.0-or-later

apiVersion: v1
kind: Service
metadata:
  name: openpgp-ca
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
