apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: openpgp-ca
  name: openpgp-ca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
