# SPDX-FileCopyrightText: 2021 Danny Grove <danny@drgrovellc.com>
# SPDX-License-Identifier: GPL-3.0-or-later

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: openpgp-ca
  name: openpgp-ca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
