# SPDX-FileCopyrightText: 2021 Danny Grove <danny@drgrovellc.com>
# SPDX-License-Identifier: GPL-3.0-or-later

apiVersion: apps/v1
kind: Deployment
metadata:
  name: openpgp-ca
spec:
  template:
    spec:
      initContainers:
        - name: init
          env:
            - name: DOMAIN
              value: "example.com"
